zad1: zad1.cpp Fifo.o Lifo.o Node.o
	g++ -o zad1 zad1.cpp Fifo.o Lifo.o Node.o

Fifo.o: Fifo.cpp Fifo.hpp
	g++ -c Fifo.cpp

Lifo.o: Lifo.cpp Lifo.hpp
	g++ -c Lifo.cpp

Node.o: Node.cpp Node.hpp
	g++ -c Node.cpp

